### ISSUE TITLE
Is a 1.18.2 port possible?

### ISSUE THREAD

**Issue by ConqAra** [Roundaround/mc-fabric-stackables#11]
I would like a 1.18.2 port if possible! This mod is just what I've wanted!

**Comment by Roundaround** [comment]
Unfortunately I'm probably not going to be touching any version less than 1.20 going forward. In order to back port any further I'd have to recreate all the utilities and helpers in my common library code for the earlier Minecraft versions, and given all the drastic changes Mojang made to UIs and menus in 1.19 and 1.20, this will end up being a lot of work. Sadly I just don't have the time to do it on my own.
