### ISSUE TITLE
[FEATURE] Compatibility with the More Music Discs mod

### ISSUE THREAD

**Issue by nco2k** [Roundaround/mc-fabric-stackables#14]
discs from the [More Music Discs](https://modrinth.com/mod/more-music-discs) mod arent affected by Stackables. any chance you could change that?

**Comment by Roundaround** [comment]
Hopefully.....this should be fixed with 2.0.0. They don't have their source code published anywhere, but I've refactored Stackables to utilized tags now. If More Music Discs for some reason doesn't work with it by default now, then you should be able to add compatibility with a data pack adding all of their new music discs to the `stackables:music_discs` tag.

At the moment 2.0.0 is only out for 1.20.3/1.20.4, but I hope to backport it to the earlier 1.20-1.20.2 versions soon.
