### ISSUE TITLE
Bugs: cases when whole stack of vanilla unstackables is consumed

### ISSUE THREAD

**Issue by CartboardKnight** [Roundaround/mc-fabric-stackables#9]
As of this moment I have found two such bugs:

1. Eating from a stack of suspicious stew returns one bowl and no suspicious stew It doesn't happen with normal mushroom stew. It was dandelion / saturation stew in my case.
2. Using multiple books while enchanting an item consumes all books. It was stack of mending books in my case.

I did not test it extensively. There may be other such cases. Just wanted to let You know.

**Comment by TheOnlyMann** [comment]
same problem. neat

**Comment by Roundaround** [comment]
Thanks for reporting! I'll try to get to this as soon as I can, but I've been pretty busy lately.

Unfortunately these kinds of issues are absolutely everywhere because the base game expects all these items to have a max stack size of 1 and the code makes some shortcuts with that assumption. I tried to track them all down but I'm always finding more. Please if you discover more I would really appreciate it if you'd report them!

**Comment by Roundaround** [comment]
Just fixed these two cases. Check out 1.3.1 on Modrinth!
